name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Maven Install
      run: mvn install -B -V -DskipTests -Dair.check.skip-all
    - name: Maven Tests
      run: mvn install -B
